// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SpecFlow.Retry.Sample
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("SampleFeature2", SourceFile="SampleFeature2.feature", SourceLine=0)]
    public partial class SampleFeature2Feature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "SampleFeature2", "", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void AddTwoNumbers(string name, string[] exampleTags)
        {
            System.Exception lastException = null;
            string configRetryCount = System.Configuration.ConfigurationManager.AppSettings["retryCount"];
            int retryCount = 0;
            if ((string.IsNullOrEmpty(configRetryCount) != true))
            {
                retryCount = System.Convert.ToInt32(configRetryCount);
            }
            for (int i = 0; (i <= retryCount); i = (i + 1))
            {
                try
                {
                    this.AddTwoNumbersInternal(name, exampleTags);
                    return;
                }
                catch (System.Exception exc)
                {
                    lastException = exc;
                }
                if (((i + 1) 
                            <= retryCount))
                {
                    testRunner.OnScenarioEnd();
                }
            }
            if ((lastException != null))
            {
                throw lastException;
            }
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add two numbers, Person 1", new string[] {
                "HA-10"}, SourceLine=7)]
        public virtual void AddTwoNumbers_Person1()
        {
            this.AddTwoNumbers("Person 1", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add two numbers, Person 2", new string[] {
                "HA-10"}, SourceLine=8)]
        public virtual void AddTwoNumbers_Person2()
        {
            this.AddTwoNumbers("Person 2", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add two numbers, Person 3", new string[] {
                "HA-10"}, SourceLine=9)]
        public virtual void AddTwoNumbers_Person3()
        {
            this.AddTwoNumbers("Person 3", ((string[])(null)));
        }
        
        private void AddTwoNumbersInternal(string name, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "HA-10"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add two numbers", @__tags);
            this.ScenarioSetup(scenarioInfo);
            testRunner.Given(string.Format("\"{0}\" failed in exam", name), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
            TechTalk.SpecFlow.ScenarioContext.Current["ScenarioExample"] = name;
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add two numbers  without examples", new string[] {
                "HA-20"}, SourceLine=13)]
        public virtual void AddTwoNumbersWithoutExamples()
        {
            System.Exception lastException = null;
            string configRetryCount = System.Configuration.ConfigurationManager.AppSettings["retryCount"];
            int retryCount = 0;
            if ((string.IsNullOrEmpty(configRetryCount) != true))
            {
                retryCount = System.Convert.ToInt32(configRetryCount);
            }
            for (int i = 0; (i <= retryCount); i = (i + 1))
            {
                try
                {
                    this.AddTwoNumbersWithoutExamplesInternal();
                    return;
                }
                catch (System.Exception exc)
                {
                    lastException = exc;
                }
                if (((i + 1) 
                            <= retryCount))
                {
                    testRunner.OnScenarioEnd();
                }
            }
            if ((lastException != null))
            {
                throw lastException;
            }
        }
        
        private void AddTwoNumbersWithoutExamplesInternal()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add two numbers  without examples", new string[] {
                        "HA-20"});
            this.ScenarioSetup(scenarioInfo);
            testRunner.Given("\"Person 1\" failed in exam", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
            TechTalk.SpecFlow.ScenarioContext.Current["ScenarioExample"] = "";
            this.ScenarioCleanup();
        }
        
        public virtual void AddTwoNumbers2(string name, string designation, string[] exampleTags)
        {
            System.Exception lastException = null;
            string configRetryCount = System.Configuration.ConfigurationManager.AppSettings["retryCount"];
            int retryCount = 0;
            if ((string.IsNullOrEmpty(configRetryCount) != true))
            {
                retryCount = System.Convert.ToInt32(configRetryCount);
            }
            for (int i = 0; (i <= retryCount); i = (i + 1))
            {
                try
                {
                    this.AddTwoNumbers2Internal(name, designation, exampleTags);
                    return;
                }
                catch (System.Exception exc)
                {
                    lastException = exc;
                }
                if (((i + 1) 
                            <= retryCount))
                {
                    testRunner.OnScenarioEnd();
                }
            }
            if ((lastException != null))
            {
                throw lastException;
            }
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add two numbers2, Person 1", new string[] {
                "HA-30"}, SourceLine=21)]
        public virtual void AddTwoNumbers2_Person1()
        {
            this.AddTwoNumbers2("Person 1", "Developer2", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add two numbers2, Person 2", new string[] {
                "HA-30"}, SourceLine=22)]
        public virtual void AddTwoNumbers2_Person2()
        {
            this.AddTwoNumbers2("Person 2", "Developer2", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add two numbers2, Person 3", new string[] {
                "HA-30"}, SourceLine=23)]
        public virtual void AddTwoNumbers2_Person3()
        {
            this.AddTwoNumbers2("Person 3", "Director2", ((string[])(null)));
        }
        
        private void AddTwoNumbers2Internal(string name, string designation, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "HA-30"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add two numbers2", @__tags);
            this.ScenarioSetup(scenarioInfo);
            testRunner.Given(string.Format("\"{0}\" failed in exam", name), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
            TechTalk.SpecFlow.ScenarioContext.Current["ScenarioExample"] = name;
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
